[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  # Next.js configuration
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Client-side routing
[[redirects]]
  from = "/*"
  to = "/_not-found"
  status = 404

# Required for Next.js API routes
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
